version: 2
jobs:
    build-debian-stretch:
        docker:
            - image: it4smart/debian-stretch-cross:v1.0.0
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Create changelog
                command: ./changelog.sh unifi-controller-it4smart stretch  > debian/changelog
            - run:
                name: Build package
                command: dpkg-buildpackage -us -uc
            - run:
                name: List directory
                command: |
                    pwd
                    ls -l 
            - store_artifacts:
                path: ~/repo