version: 2
jobs:
    build-debian-stretch-armhf:
        docker:
            - image: it4smart/debian-stretch-cross:v1.2.1
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Download source
                command: |
                    export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                    wget https://codeload.github.com/IT4smart/unifi-controller-it4smart/tar.gz/${GIT_TAG} -O unifi-controller-it4smart_${GIT_TAG//v}.orig.tar.gz
            - run:
                name: Create changelog
                command: ./changelog.sh unifi-controller-it4smart stretch deb9 > debian/changelog
            - run:
                name: Build package
                command: dpkg-buildpackage -us -uc --host-arch armhf
            - add_ssh_keys:
                fingerprints:
                    - "77:1e:e6:8b:6f:f5:1c:cc:c9:ca:92:02:1e:4b:c6:5f"
            - run:
                name: Upload package
                command: scp -o StrictHostKeyChecking=no $(ls ~/*.deb) uploader@mirror.it4smart.eu:/var/repositories/debian/incoming/stretch/
            - store_artifacts:
                path: ~/
    build-debian-buster-armhf:
        docker:
            - image: it4smart/debian-buster-cross:v1.2.1
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Download source
                command: |
                    export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                    wget https://codeload.github.com/IT4smart/unifi-controller-it4smart/tar.gz/${GIT_TAG} -O unifi-controller-it4smart_${GIT_TAG//v}.orig.tar.gz
            - run:
                name: Create changelog
                command: ./changelog.sh unifi-controller-it4smart stretch deb10 > debian/changelog
            - run:
                name: Build package
                command: dpkg-buildpackage -us -uc --host-arch armhf
            - add_ssh_keys:
                fingerprints:
                    - "77:1e:e6:8b:6f:f5:1c:cc:c9:ca:92:02:1e:4b:c6:5f"
            - run:
                name: Upload package
                command: scp -o StrictHostKeyChecking=no $(ls ~/*.deb) uploader@mirror.it4smart.eu:/var/repositories/debian/incoming/buster/
            - store_artifacts:
                path: ~/
    build-debian-stretch-armhf-snapshot:
        docker:
            - image: it4smart/debian-stretch-cross:v1.2.1
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Download source
                command: |
                    export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                    export GIT_COMMIT=${CIRCLE_SHA1:0:7}
                    wget https://codeload.github.com/IT4smart/unifi-controller-it4smart/zip/${CIRCLE_BRANCH} -O unifi-controller-it4smart_${GIT_TAG//v}+git-${GIT_COMMIT}.orig.tar.gz
            - run:
                name: Create changelog
                command: ./changelog.sh unifi-controller-it4smart stretch deb10 > debian/changelog
            - run:
                name: Build package
                command: dpkg-buildpackage -us -uc --host-arch armhf
            - run:
                name: Save build
                command: |
                    mkdir -p ~/build
                    mv ~/*.deb ~/build/
            - store_artifacts:
                path: ~/
            - persist_to_workspace:
                root: ~/
                paths:
                    - build/*
    test-debian-stretch-armhf-snapshot:
        machine: true
        working_directory: ~/repo
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - run:
                name: Download and compile qemu
                command: |
                    wget https://download.qemu.org/qemu-4.2.0.tar.xz
                    tar xvJf qemu-4.2.0.tar.xz
                    cd qemu-4.2.0
                    ./configure --target-list=arm-softmmu,aarch64-softmmu
                    make
            - run:
                name: Download latest raspbian stretch lite
                command: |
                    wget https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip
                    mv 2019-04-08-raspbian-stretch-lite.zip raspbian-stretch-lite.zip
                    unzip raspbian-stretch-lite.zip
            - run:
                name: Convert img to qcow2
                command: qemu-4.2.0/qemu-img convert -f raw -O qcow2 $(ls *.img) raspbian-lite.qcow2
            - run:
                name: Resize raspbian lite image
                command: qemu-4.2.0/qemu-img resize raspbian-lite.qcow2 +1G
            - run:
                name: Check if raspbian lite image is OK
                command: qemu-4.2.0/qemu-img info raspbian-lite.qcow2
            - run:
                name: Run raspbian lite
                command: qemu-4.2.0/arm-softmmu/qemu-system-arm -M raspi2 -hda raspbian-lite.qcow2

workflows:
    version: 2
    release:
        jobs:
            - build-debian-stretch-armhf:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v[0-9]+\.[0-9]+\.[0-9]+/
            - build-debian-buster-armhf:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /v[0-9]+\.[0-9]+\.[0-9]+/
    snapshot:
        jobs:
            - build-debian-stretch-armhf-snapshot