version: 2
jobs:
    build-debian-stretch-armhf:
        docker:
            - image: it4smart/debian-stretch-cross:v1.0.0
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Download source
                command: |
                    export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                    wget https://codeload.github.com/IT4smart/unifi-controller-it4smart/tar.gz/${GIT_TAG} -O unifi-controller-it4smart_${GIT_TAG//v}.orig.tar.gz
            - run:
                name: Create changelog
                command: ./changelog.sh unifi-controller-it4smart stretch  > debian/changelog
            - run:
                name: Build package
                command: dpkg-buildpackage -us -uc --host-arch armhf
            - run:
                name: List directory
                command: |
                    pwd
                    ls -l 
            - store_artifacts:
                path: ~/

workflows:
    version: 2
    release:
        jobs:
            - build-debian-stretch-armhf