name: CI
on:
    push:
    pull_request:
        branches: [master]

jobs:
    testing:
        container: it4smart/debian-stretch-cross:v1.1.0
        steps:
            - uses: actions/checkout@v2
            - run: |
                pwd
                ls -l
