name: CI
on:
    push:
    pull_request:
        branches: [master]

jobs:
    testing:
        runs-on: ubuntu-latest
        container: debian:stable
#            image: it4smart/debian-stretch-cross:v1.1.0
        steps:
            - run: |
                pwd
                ls -l
            - uses: actions/checkout@v2
            - run: |
                pwd
                ls -l
